Create frontend interface
qua-platform/qua-qsim pull request #9
Opened 2024-06-03 21:51 UTC by Piwakk

Closes: #4 (as part of unitaryHACK 2024)

Implement a FastAPI backend and a Dash frontend (http://127.0.0.1:8000/frontend/) to visualize the simulated results and the Qiskit Pulse Schedule of a QUA program.

Requirements in #4 are respected. One non-trivial issue remains: the code for plotting the simulated results is not transmitted through the API, so it has to be the same for all programs, which is obviously not possible. I'm not sure about what would be the best here (the current implementation uses the plotting code of `test_rabi.py`).

![image](https://github.com/qua-platform/qua-qsim/assets/11032610/52628f43-687d-4a76-87f4-86da3ac2f1d4)

2024-06-03 21:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qua-platform/qua-qsim?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qua-platform/qua-qsim?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qua-platform/qua-qsim?pullRequest=9) it.</sub>

2024-06-04 06:53 UTC, nulinspiratie requested changes
Fantastic Piwakk! I managed to get it working locally, and it looks good and matches the requirements.
I agree with your comment regarding plotting, it requires some more thinking, but that's for a future PR.

Before approving, I found that a few new packages are introduced, could you add these to the requirements? The packages are `requests`, `fastapi`, `uvicorn`, `dash_bootstrap_components`.

And again, nicely done!

2024-06-04 17:30 UTC, Piwakk commented
> Fantastic Piwakk! I managed to get it working locally, and it looks good and matches the requirements. I agree with your comment regarding plotting, it requires some more thinking, but that's for a future PR.
> 
> Before approving, I found that a few new packages are introduced, could you add these to the requirements? The packages are `requests`, `fastapi`, `uvicorn`, `dash_bootstrap_components`.
> 
> And again, nicely done!

Thanks for the feedback! 😊 I've added the dependencies.

2024-06-05 20:57 UTC, nulinspiratie approved these changes
Great job!

2024-06-05 20:57 UTC, merged